# Values from a small sedan
# See logic/src/game/config.rs for an explanation-ish of these values

mass: 1200.0
inertia_scale: 1.0
half_width: 0.8
center_of_gravity_to_front: 2.0
center_of_gravity_to_rear: 2.0
center_of_gravity_to_front_axle: 1.25
center_of_gravity_to_rear_axle: 1.25
center_of_gravity_height: 0.55
wheel_radius: 0.3
wheel_width: 0.2
tire_grip: 2.0
lock_grip: 0.7
engine_force: 8000.0
brake_force: 12000.0
e_brake_force: 4800.0 # should be approximately brake_force / 2.5
weight_transfer: 0.2
max_steer: 0.6
corner_stiffness_front:  5.0
corner_stiffness_rear: 5.2
air_resist: 2.5
roll_resist: 8.0
